---
extends:
  - eslint:recommended
  - plugin:prettier/recommended
  - plugin:jest/recommended
plugins:
  - import
parser: babel-eslint
parserOptions:
  sourceType: script
root: true
env:
  es6: true
  node: true
  jest: true
rules:
  eqeqeq: error
  curly: error
  import/no-extraneous-dependencies:
    - error
    - devDependencies: ["tests*/**", "scripts/**", "build/**"]
  no-else-return: error
  no-inner-declarations: error
  no-useless-return: error
  no-var: error
  one-var:
    - error
    - never
  object-shorthand: error
  prefer-arrow-callback: error
  prefer-const: error
  prefer-destructuring: error
  prefer-template: error
  strict: error
  symbol-description: error
overrides:
  - files: "tests/**/*.js"
    rules:
      strict: 0
    globals:
      run_spec: true
